spring:
  applicaton:
    name: finex-orderbook
  zipkin:
    baseUrl: ${ZIPKIN_URI}
    sender:
      type: ${ZIPKIN_SENDER_TYPE}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

server:
  port: 8443
  ssl:
    enabled: true
    key-store: ${TLS_KEYSTORE}
    key-store-password: ${TLS_KEYSTORE_PASSWORD}
    key-store-type: PKCS12

eureka:
  client:
    fetch-registry: true
    securePortEnabled: true
    serviceUrl:
      defaultZone: ${ATLAS_DISCOVERY_URI}
  instance:
    nonSecurePortEnabled: false
    securePortEnabled: true
    securePort: 443
    statusPageUrl: https://${ATLAS_DISCOVERY_CLIENT_HOSTNAME}:${eureka.instance.securePort}/actuator/info
    healthCheckUrl: https://${ATLAS_DISCOVERY_CLIENT_HOSTNAME}:${eureka.instance.securePort}/actuator/health
    preferIpAddress: false
    hostname: ${ATLAS_DISCOVERY_CLIENT_HOSTNAME}
