name: maven

on:
  push:
    branches-ignore:
      - 'master'
      - 'release*'

jobs:

  compile:
    name: Maven Compile
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Maven Compile - Discovery
        run: cd discovery/ && mvn -B clean package -DskipTests
      - name: Maven Compile: - Orderbooks
        run: cd orderbooks/ && mvn -B clean verify
      - name: Maven Compile: - Trades
        run: cd trades/ && mvn -B clean verify
